0~~~~                            ~~ Monitor: f6ec28cb-7220-475e-848f-1b7eb94fd030
   2018-05-30 15h42.40.4621284 i Topic: CK.Monitoring.DispatcherSink
   2018-05-30 15h42.40.5255097   > Initializing TextFile handler (MaxCountPerFile = 20000).
   2018-05-30 15h42.40.5429785   < 
1~~~~                            ~~ Monitor: bce8505d-a418-4707-8417-5a60b2723b98
   2018-05-30 15h42.44.8090075 W Failed to connect to WebApp (1).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h42.47.4351268 W Failed to connect to WebApp (2).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h42.49.6536599 W Failed to connect to WebApp (3).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h42.51.9116181 W Failed to connect to WebApp (4).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h42.54.1591666 W Failed to connect to WebApp (5).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h42.56.4498659 W Failed to connect to WebApp (6).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h42.58.6737250 W Failed to connect to WebApp (7).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.00.9076340 W Failed to connect to WebApp (8).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.03.1724264 W Failed to connect to WebApp (9).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.05.4809801 W Failed to connect to WebApp (10).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.10.7803727 W Failed to connect to WebApp (1).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.13.0307474 W Failed to connect to WebApp (2).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.15.2956036 W Failed to connect to WebApp (3).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.17.5694780 W Failed to connect to WebApp (4).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.19.8034584 W Failed to connect to WebApp (5).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.22.0362915 W Failed to connect to WebApp (6).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.24.2988389 W Failed to connect to WebApp (7).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.25.2115141 i Folder 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\TestStores' has been cleaned up.
   2018-05-30 15h43.25.2669112 i Switching console log ON.
   2018-05-30 15h43.25.6002928 i Using default connection string: Server=.;Database=master;Integrated Security=SSPI
   2018-05-30 15h43.26.6716745 W Failed to connect to WebApp (8).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.26.9291940 i > Running DBSetup on Database:TEST_WEB_APP_AUTH, Collation:Latin1_General_100_BIN2, CompatibilityLevel:130.
   2018-05-30 15h43.26.9631311 i | > Ensuring database 'Database:TEST_WEB_APP_AUTH, Collation:Latin1_General_100_BIN2, CompatibilityLevel:130'.
   2018-05-30 15h43.27.1477873 i | <  | 1 conclusion:
                                 |    | Database already exists, collation and compatiblity level match.
   2018-05-30 15h43.27.1677533 i | > Running StObjSetup.
   2018-05-30 15h43.27.2216676 i | | No 'CKSetup/DefaultBinPaths' configuration. Using current BinFolder.
   2018-05-30 15h43.27.2867715 i | | > Running Setup on 'C:\Dev\LocalFeed\CI\CKSetupStore' for the first time.
   2018-05-30 15h43.27.2872713 i | | | No 'CKSetup/AutoRegisterLocalComponentPaths' components specified.
   2018-05-30 15h43.27.2872713 i | | < 
   2018-05-30 15h43.27.2882691 i | | Using store 'C:\Dev\LocalFeed\CI\CKSetupStore'.
   2018-05-30 15h43.27.2887684 i | | Using remote 'file:///C:/Dev/LocalFeed/CI/CKSetupStore'.
   2018-05-30 15h43.27.5068660   | | Opened store with 2 components.
   2018-05-30 15h43.27.5078611   | | Local store opened on : 'C:\Dev\LocalFeed\CI\CKSetupStore'.
   2018-05-30 15h43.27.5223338   | | > Creating client remote store on 'file:///C:/Dev/LocalFeed/CI/CKSetupStore'.
   2018-05-30 15h43.27.5258275   | | | Opened store with 2 components.
   2018-05-30 15h43.27.5263268   | | | Local store opened on : 'C:\Dev\LocalFeed\CI\CKSetupStore'.
   2018-05-30 15h43.27.5273242   | | < 
   2018-05-30 15h43.27.5288213 i | | > Running Setup.
   2018-05-30 15h43.27.5407986   | | | > Initializing SetupContext (ignoring signatures).
   2018-05-30 15h43.27.6935152 i | | | | <Root>
                                 | | | |     <CKSetup>
                                 | | | |       <BinPaths>
                                 | | | |         <BinPath>C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461</BinPath>
                                 | | | |       </BinPaths>
                                 | | | |       <Dependencies />
                                 | | | |       <EngineAssemblyQualifiedName>CK.Setup.StObjEngine, CK.StObj.Engine</EngineAssemblyQualifiedName>
                                 | | | |     </CKSetup>
                                 | | | |     <Configuration>
                                 | | | |       <AppContextAssemblyGeneratedDirectoryTarget>C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461</AppContextAssemblyGeneratedDirectoryTarget>
                                 | | | |       <GenerateSourceFiles>true</GenerateSourceFiles>
                                 | | | |       <Assemblies />
                                 | | | |       <Types />
                                 | | | |       <Aspect Type="CK.Setup.SetupableAspectConfiguration, CK.Setupable.Model" Version="1" />
                                 | | | |       <Aspect Type="CK.Setup.SqlSetupAspectConfiguration, CK.SqlServer.Setup.Model">
                                 | | | |         <Databases />
                                 | | | |         <DefaultDatabaseConnectionString>Data Source=.;Initial Catalog=TEST_WEB_APP_AUTH;Integrated Security=True</DefaultDatabaseConnectionString>
                                 | | | |         <GlobalResolution>true</GlobalResolution>
                                 | | | |       </Aspect>
                                 | | | |     </Configuration>
                                 | | | |   </Root>
   2018-05-30 15h43.27.6935152 i | | | | Configuration BasePath is empty: using current directory 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461'.
   2018-05-30 15h43.27.6985055 i | | | | > Reading binary folders.
   2018-05-30 15h43.27.7034964 i | | | | | > Reading files from 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461'.
   2018-05-30 15h43.28.5877403 i | | | | | < 
   2018-05-30 15h43.28.5887394 i | | | | <  | 1 conclusion:
                                 | | | |    | 1 folders read.
   2018-05-30 15h43.28.7851677 i | | | | Created temporary Working Directory: C:\Users\olivi\AppData\Local\Temp\CKSetup2018-05-30 15h43.28.7826758\.
   2018-05-30 15h43.28.7861668   | | | < 
   2018-05-30 15h43.28.7931533 i | | | > Resolving runtime support for 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461\'.
   2018-05-30 15h43.28.8490524 i | | | | > Creating runtime dependencies resolver for C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461\.
   2018-05-30 15h43.28.9972748 W | | | | | Failed to connect to WebApp (9).
                                 | | | | |    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                 | | | | |    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                 | | | | |    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 | | | | |    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                 | | | | |    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                 | | | | |    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                 | | | | |    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                 | | | | |    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 | | | | |    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                 | | | | |    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                 | | | | |    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                 | | | | |    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                 | | | | |    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 | | | | |    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                 | | | | |    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                 | | | | |    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                 | | | | |    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                 | | | | |    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                 | | | | |    |  |  | Message:    Impossible de se connecter au serveur distant
                                 | | | | |    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                 | | | | |    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                 | | | | |    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                 | | | | |    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                 | | | | |    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                 | | | | |    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                 | | | | |    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                 | | | | |    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                 | | | | |    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                 | | | | |    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                 | | | | |    |  |  └─────────────────────────────────────────────────────────────────────────
                                 | | | | |    |  └─────────────────────────────────────────────────────────────────────────
                                 | | | | |    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h43.29.0077567 i | | | | | > Detecting runtimes for: CK.Setupable.Model/Net461, CK.SqlServer.Setup.Model/Net461, CK.StObj.Model/Net461
   2018-05-30 15h43.29.0476802 i | | | | | | Multiple possible runtime: Net461, Net462, Net47.
   2018-05-30 15h43.29.0531695 i | | | | | <  | 1 conclusion:
                                 | | | | |    | Lowest selected runtime: Net461.
   2018-05-30 15h43.29.1130586 i | | | | < 
   2018-05-30 15h43.29.1150551 i | | | | > Initializing root dependencies.
   2018-05-30 15h43.29.1440013   | | | | | Adding required dependency -> CK.Setupable.Runtime/6.0.1-C0006-local.
   2018-05-30 15h43.29.1459979   | | | | | Adding required dependency -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local.
   2018-05-30 15h43.29.1464959   | | | | | Adding required dependency -> CK.StObj.Runtime/6.0.1-C0006-local.
   2018-05-30 15h43.29.1499927   | | | | | Adding required dependency -> CKSetup.Runner/6.0.1-C0008-local.
   2018-05-30 15h43.29.1554811 i | | | | | > Using donwloader.
   2018-05-30 15h43.29.1694539 i | | | | | | <Missing Runtime="Net461">
                                 | | | | | |     <Dependency Name="CK.Setupable.Runtime" Version="6.0.1-C0006-local" />
                                 | | | | | |     <Dependency Name="CK.SqlServer.Setup.Runtime" Version="6.0.1-C0006-local" />
                                 | | | | | |     <Dependency Name="CK.StObj.Runtime" Version="6.0.1-C0006-local" />
                                 | | | | | |     <Dependency Name="CKSetup.Runner" Version="6.0.1-C0008-local" />
                                 | | | | | |   </Missing>
   2018-05-30 15h43.29.1729472   | | | | | | > Creating client remote store on 'file:///C:/Dev/LocalFeed/Release/CKSetupStore'.
   2018-05-30 15h43.29.1889201   | | | | | | | Opened store with 30 components.
   2018-05-30 15h43.29.1889201   | | | | | | | Local store opened on : 'C:\Dev\LocalFeed\Release\CKSetupStore'.
   2018-05-30 15h43.29.1889201   | | | | | | < 
   2018-05-30 15h43.29.1914169 i | | | | | | > Using prototype store (file:///C:/Dev/LocalFeed/Release/CKSetupStore) first and then specified remote store (file:///C:/Dev/LocalFeed/CI/CKSetupStore) if needed.
   2018-05-30 15h43.29.1988982   | | | | | | | > Download from store: file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h43.29.2053885 i | | | | | | | | > Finding locally available components.
   2018-05-30 15h43.29.2058865 i | | | | | | | | | > Resolving dependencies for Net461.
   2018-05-30 15h43.29.2068847 W | | | | | | | | | | Not found: -> CK.Setupable.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.2078825 W | | | | | | | | | | Not found: -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.2078825 W | | | | | | | | | | Not found: -> CK.StObj.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.2078825 W | | | | | | | | | | Not found: -> CKSetup.Runner/6.0.1-C0008-local dependency.
   2018-05-30 15h43.29.2078825 i | | | | | | | | | < 
   2018-05-30 15h43.29.2078825 i | | | | | | | | < 
   2018-05-30 15h43.29.2183635   | | | | | | | | > Creating client remote store on 'https://cksetup.invenietis.net/'.
   2018-05-30 15h43.29.2223552   | | | | | | | | < 
   2018-05-30 15h43.29.2223552 i | | | | | | | | > Requesting Prototype store to complete the export.
   2018-05-30 15h43.29.2228541 i | | | | | | | | | > No remote store has been specified. Using prototype store only (https://cksetup.invenietis.net/).
   2018-05-30 15h43.29.2228541   | | | | | | | | | | > Download from store: https://cksetup.invenietis.net/.
   2018-05-30 15h43.29.9146240 i | | | | | | | | | | | > Starting import from https://cksetup.invenietis.net/.
   2018-05-30 15h43.29.9181181 i | | | | | | | | | | | | > Starting components import.
   2018-05-30 15h43.29.9216113 i | | | | | | | | | | | | < 
   2018-05-30 15h43.29.9261028 i | | | | | | | | | | | < 
   2018-05-30 15h43.29.9261028   | | | | | | | | | | < 
   2018-05-30 15h43.29.9261028 i | | | | | | | | | < 
   2018-05-30 15h43.29.9261028 i | | | | | | | | < 
   2018-05-30 15h43.29.9281051 i | | | | | | | | > Starting import from file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h43.29.9281051 i | | | | | | | | | > Starting components import.
   2018-05-30 15h43.29.9285987 i | | | | | | | | | < 
   2018-05-30 15h43.29.9285987 i | | | | | | | | < 
   2018-05-30 15h43.29.9285987   | | | | | | | < 
   2018-05-30 15h43.29.9370827   | | | | | | | > Download from store: file:///C:/Dev/LocalFeed/CI/CKSetupStore.
   2018-05-30 15h43.29.9370827 i | | | | | | | | > Finding locally available components.
   2018-05-30 15h43.29.9370827 i | | | | | | | | | > Resolving dependencies for Net461.
   2018-05-30 15h43.29.9370827 W | | | | | | | | | | Not found: -> CK.Setupable.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.9370827 W | | | | | | | | | | Not found: -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.9370827 W | | | | | | | | | | Not found: -> CK.StObj.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.9375821 W | | | | | | | | | | Not found: -> CKSetup.Runner/6.0.1-C0008-local dependency.
   2018-05-30 15h43.29.9375821 i | | | | | | | | | < 
   2018-05-30 15h43.29.9375821 i | | | | | | | | < 
   2018-05-30 15h43.29.9375821   | | | | | | | | > Creating client remote store on 'file:///C:/Dev/LocalFeed/Release/CKSetupStore'.
   2018-05-30 15h43.29.9620396   | | | | | | | | | Opened store with 30 components.
   2018-05-30 15h43.29.9620396   | | | | | | | | | Local store opened on : 'C:\Dev\LocalFeed\Release\CKSetupStore'.
   2018-05-30 15h43.29.9620396   | | | | | | | | < 
   2018-05-30 15h43.29.9620396 i | | | | | | | | > Requesting Prototype store to complete the export.
   2018-05-30 15h43.29.9625358 i | | | | | | | | | > No remote store has been specified. Using prototype store only (file:///C:/Dev/LocalFeed/Release/CKSetupStore).
   2018-05-30 15h43.29.9625358   | | | | | | | | | | > Download from store: file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h43.29.9625358 i | | | | | | | | | | | > Finding locally available components.
   2018-05-30 15h43.29.9625358 i | | | | | | | | | | | | > Resolving dependencies for Net461.
   2018-05-30 15h43.29.9625358 W | | | | | | | | | | | | | Not found: -> CK.Setupable.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.9630347 W | | | | | | | | | | | | | Not found: -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.9630347 W | | | | | | | | | | | | | Not found: -> CK.StObj.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h43.29.9630347 W | | | | | | | | | | | | | Not found: -> CKSetup.Runner/6.0.1-C0008-local dependency.
   2018-05-30 15h43.29.9630347 i | | | | | | | | | | | | < 
   2018-05-30 15h43.29.9630347 i | | | | | | | | | | | < 
   2018-05-30 15h43.29.9630347   | | | | | | | | | | | > Creating client remote store on 'https://cksetup.invenietis.net/'.
   2018-05-30 15h43.29.9630347   | | | | | | | | | | | < 
   2018-05-30 15h43.29.9630347 i | | | | | | | | | | | > Requesting Prototype store to complete the export.
   2018-05-30 15h43.29.9630347 i | | | | | | | | | | | | > No remote store has been specified. Using prototype store only (https://cksetup.invenietis.net/).
   2018-05-30 15h43.29.9630347   | | | | | | | | | | | | | > Download from store: https://cksetup.invenietis.net/.
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | | | | > Starting import from https://cksetup.invenietis.net/.
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | | | | | > Starting components import.
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | | | | | < 
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | | | | < 
   2018-05-30 15h43.30.0468787   | | | | | | | | | | | | | < 
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | | < 
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | < 
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | > Starting import from file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h43.30.0468787 i | | | | | | | | | | | | > Starting components import.
   2018-05-30 15h43.30.0473785 i | | | | | | | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | | | | | | | < 
   2018-05-30 15h43.30.0473785   | | | | | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | | | | > Starting import from file:///C:/Dev/LocalFeed/CI/CKSetupStore.
   2018-05-30 15h43.30.0473785 i | | | | | | | | | > Starting components import.
   2018-05-30 15h43.30.0473785 i | | | | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | | | | < 
   2018-05-30 15h43.30.0473785   | | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | | < 
   2018-05-30 15h43.30.0473785 i | | | | | < 
   2018-05-30 15h43.30.0493759 E | | | | | Missing required dependencies: -> CK.Setupable.Runtime/6.0.1-C0006-local, -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local, -> CK.StObj.Runtime/6.0.1-C0006-local, -> CKSetup.Runner/6.0.1-C0008-local.
   2018-05-30 15h43.30.0493759 i | | | | < 
   2018-05-30 15h43.30.0498726 i | | | < 
   2018-05-30 15h43.30.0508709 i | | | > Deleting temporary Working Directory.
   2018-05-30 15h43.30.0523676 i | | | < 
   2018-05-30 15h43.30.0523676 i | | <  | 1 conclusion:
                                 | |    | Failed
   2018-05-30 15h43.30.0558639 i | | > Closing Store.
   2018-05-30 15h43.30.0568595 i | | | > Closing Store.
   2018-05-30 15h43.30.0932920 i | | | < 
   2018-05-30 15h43.30.0932920 i | | < 
   2018-05-30 15h43.30.0932920 i | | > Closing Store.
   2018-05-30 15h43.30.0932920 i | | | > Closing Store.
   2018-05-30 15h43.30.0937914 i | | | < 
   2018-05-30 15h43.30.0937914 i | | < 
   2018-05-30 15h43.30.0937914 i | < 
   2018-05-30 15h43.30.0937914 i < 
   2018-05-30 15h43.34.0810890 W Failed to connect to WebApp (10).
                                    ┌──────────────────────────■ Exception: HttpRequestException ■──────────────────────────
                                    | Message:    Une erreur s'est produite lors de l'envoi de la demande.
                                    | Stack:         à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClient.Handler.<SendAsync>d__2.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à CK.AspNet.Tester.TestClientBase.<Get>d__20.MoveNext()
                                    |             --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                                    |                à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                    |                à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                    |                à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                                    |                à WebApp.Tests.WebAppHelper.<WaitForWebAppAnswer>d__5.MoveNext()
                                    |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: WebException ■──────────────────────────
                                    |  |  | Message:    Impossible de se connecter au serveur distant
                                    |  |  | Stack:         à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                                    |  |  |                à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                                    |  |  |  ┌──────────────────────────■ [Inner Exception] ■──────────────────────────
                                    |  |  |  |  ┌──────────────────────────■ Exception: SocketException ■──────────────────────────
                                    |  |  |  |  | Message:    Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:4324
                                    |  |  |  |  | Stack:         à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                                    |  |  |  |  |                à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
                                    |  |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
   2018-05-30 15h44.17.5616741 i > Running DBSetup on Database:TEST_WEB_APP_AUTH, Collation:Latin1_General_100_BIN2, CompatibilityLevel:130.
   2018-05-30 15h44.17.5621596 i | > Ensuring database 'Database:TEST_WEB_APP_AUTH, Collation:Latin1_General_100_BIN2, CompatibilityLevel:130'.
   2018-05-30 15h44.17.6235436 i | <  | 1 conclusion:
                                 |    | Database already exists, collation and compatiblity level match.
   2018-05-30 15h44.17.6235436 i | > Running StObjSetup.
   2018-05-30 15h44.17.6235436 i | | No 'CKSetup/DefaultBinPaths' configuration. Using current BinFolder.
   2018-05-30 15h44.17.6235436 i | | Using store 'C:\Dev\LocalFeed\CI\CKSetupStore'.
   2018-05-30 15h44.17.6235436 i | | Using remote 'file:///C:/Dev/LocalFeed/CI/CKSetupStore'.
   2018-05-30 15h44.17.6275357   | | Opened store with 2 components.
   2018-05-30 15h44.17.6275357   | | Local store opened on : 'C:\Dev\LocalFeed\CI\CKSetupStore'.
   2018-05-30 15h44.17.6280355   | | > Creating client remote store on 'file:///C:/Dev/LocalFeed/CI/CKSetupStore'.
   2018-05-30 15h44.17.6295322   | | | Opened store with 2 components.
   2018-05-30 15h44.17.6295322   | | | Local store opened on : 'C:\Dev\LocalFeed\CI\CKSetupStore'.
   2018-05-30 15h44.17.6295322   | | < 
   2018-05-30 15h44.17.6295322 i | | > Running Setup.
   2018-05-30 15h44.17.6295322   | | | > Initializing SetupContext (ignoring signatures).
   2018-05-30 15h44.17.6300316 i | | | | <Root>
                                 | | | |     <CKSetup>
                                 | | | |       <BinPaths>
                                 | | | |         <BinPath>C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461</BinPath>
                                 | | | |       </BinPaths>
                                 | | | |       <Dependencies />
                                 | | | |       <EngineAssemblyQualifiedName>CK.Setup.StObjEngine, CK.StObj.Engine</EngineAssemblyQualifiedName>
                                 | | | |     </CKSetup>
                                 | | | |     <Configuration>
                                 | | | |       <AppContextAssemblyGeneratedDirectoryTarget>C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461</AppContextAssemblyGeneratedDirectoryTarget>
                                 | | | |       <GenerateSourceFiles>true</GenerateSourceFiles>
                                 | | | |       <Assemblies />
                                 | | | |       <Types />
                                 | | | |       <Aspect Type="CK.Setup.SetupableAspectConfiguration, CK.Setupable.Model" Version="1" />
                                 | | | |       <Aspect Type="CK.Setup.SqlSetupAspectConfiguration, CK.SqlServer.Setup.Model">
                                 | | | |         <Databases />
                                 | | | |         <DefaultDatabaseConnectionString>Data Source=.;Initial Catalog=TEST_WEB_APP_AUTH;Integrated Security=True</DefaultDatabaseConnectionString>
                                 | | | |         <GlobalResolution>true</GlobalResolution>
                                 | | | |       </Aspect>
                                 | | | |     </Configuration>
                                 | | | |   </Root>
   2018-05-30 15h44.17.6305327 i | | | | Configuration BasePath is empty: using current directory 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461'.
   2018-05-30 15h44.17.6310307 i | | | | > Reading binary folders.
   2018-05-30 15h44.17.6315319 i | | | | | > Reading files from 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461'.
   2018-05-30 15h44.17.8281640 i | | | | | < 
   2018-05-30 15h44.17.8281640 i | | | | <  | 1 conclusion:
                                 | | | |    | 1 folders read.
   2018-05-30 15h44.17.9471032 i | | | | Created temporary Working Directory: C:\Users\olivi\AppData\Local\Temp\CKSetup2018-05-30 15h44.17.9451071\.
   2018-05-30 15h44.17.9471032   | | | < 
   2018-05-30 15h44.17.9476021 i | | | > Resolving runtime support for 'C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461\'.
   2018-05-30 15h44.17.9476021 i | | | | > Creating runtime dependencies resolver for C:\Dev\CK-AspNet-Projects\CK-AspNet-Auth\Tests\Integration\WebApp.Tests\bin\Debug\net461\.
   2018-05-30 15h44.17.9476021 i | | | | | > Detecting runtimes for: CK.Setupable.Model/Net461, CK.SqlServer.Setup.Model/Net461, CK.StObj.Model/Net461
   2018-05-30 15h44.17.9476021 i | | | | | | Multiple possible runtime: Net461, Net462, Net47.
   2018-05-30 15h44.17.9476021 i | | | | | <  | 1 conclusion:
                                 | | | | |    | Lowest selected runtime: Net461.
   2018-05-30 15h44.17.9481015 i | | | | < 
   2018-05-30 15h44.17.9481015 i | | | | > Initializing root dependencies.
   2018-05-30 15h44.17.9481015   | | | | | Adding required dependency -> CK.Setupable.Runtime/6.0.1-C0006-local.
   2018-05-30 15h44.17.9481015   | | | | | Adding required dependency -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local.
   2018-05-30 15h44.17.9481015   | | | | | Adding required dependency -> CK.StObj.Runtime/6.0.1-C0006-local.
   2018-05-30 15h44.17.9481015   | | | | | Adding required dependency -> CKSetup.Runner/6.0.1-C0008-local.
   2018-05-30 15h44.17.9481015 i | | | | | > Using donwloader.
   2018-05-30 15h44.17.9481015 i | | | | | | <Missing Runtime="Net461">
                                 | | | | | |     <Dependency Name="CK.Setupable.Runtime" Version="6.0.1-C0006-local" />
                                 | | | | | |     <Dependency Name="CK.SqlServer.Setup.Runtime" Version="6.0.1-C0006-local" />
                                 | | | | | |     <Dependency Name="CK.StObj.Runtime" Version="6.0.1-C0006-local" />
                                 | | | | | |     <Dependency Name="CKSetup.Runner" Version="6.0.1-C0008-local" />
                                 | | | | | |   </Missing>
   2018-05-30 15h44.17.9481015   | | | | | | > Creating client remote store on 'file:///C:/Dev/LocalFeed/Release/CKSetupStore'.
   2018-05-30 15h44.17.9585843   | | | | | | | Opened store with 30 components.
   2018-05-30 15h44.17.9585843   | | | | | | | Local store opened on : 'C:\Dev\LocalFeed\Release\CKSetupStore'.
   2018-05-30 15h44.17.9585843   | | | | | | < 
   2018-05-30 15h44.17.9585843 i | | | | | | > Using prototype store (file:///C:/Dev/LocalFeed/Release/CKSetupStore) first and then specified remote store (file:///C:/Dev/LocalFeed/CI/CKSetupStore) if needed.
   2018-05-30 15h44.17.9585843   | | | | | | | > Download from store: file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h44.17.9585843 i | | | | | | | | > Finding locally available components.
   2018-05-30 15h44.17.9585843 i | | | | | | | | | > Resolving dependencies for Net461.
   2018-05-30 15h44.17.9585843 W | | | | | | | | | | Not found: -> CK.Setupable.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.17.9585843 W | | | | | | | | | | Not found: -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.17.9585843 W | | | | | | | | | | Not found: -> CK.StObj.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.17.9585843 W | | | | | | | | | | Not found: -> CKSetup.Runner/6.0.1-C0008-local dependency.
   2018-05-30 15h44.17.9585843 i | | | | | | | | | < 
   2018-05-30 15h44.17.9585843 i | | | | | | | | < 
   2018-05-30 15h44.17.9585843   | | | | | | | | > Creating client remote store on 'https://cksetup.invenietis.net/'.
   2018-05-30 15h44.17.9585843   | | | | | | | | < 
   2018-05-30 15h44.17.9585843 i | | | | | | | | > Requesting Prototype store to complete the export.
   2018-05-30 15h44.17.9585843 i | | | | | | | | | > No remote store has been specified. Using prototype store only (https://cksetup.invenietis.net/).
   2018-05-30 15h44.17.9585843   | | | | | | | | | | > Download from store: https://cksetup.invenietis.net/.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | | | > Starting import from https://cksetup.invenietis.net/.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | | | | > Starting components import.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | | | | < 
   2018-05-30 15h44.18.0433244 i | | | | | | | | | | | < 
   2018-05-30 15h44.18.0433244   | | | | | | | | | | < 
   2018-05-30 15h44.18.0433244 i | | | | | | | | | < 
   2018-05-30 15h44.18.0433244 i | | | | | | | | < 
   2018-05-30 15h44.18.0433244 i | | | | | | | | > Starting import from file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | > Starting components import.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | < 
   2018-05-30 15h44.18.0433244 i | | | | | | | | < 
   2018-05-30 15h44.18.0433244   | | | | | | | < 
   2018-05-30 15h44.18.0433244   | | | | | | | > Download from store: file:///C:/Dev/LocalFeed/CI/CKSetupStore.
   2018-05-30 15h44.18.0433244 i | | | | | | | | > Finding locally available components.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | > Resolving dependencies for Net461.
   2018-05-30 15h44.18.0433244 W | | | | | | | | | | Not found: -> CK.Setupable.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.18.0433244 W | | | | | | | | | | Not found: -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.18.0433244 W | | | | | | | | | | Not found: -> CK.StObj.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.18.0433244 W | | | | | | | | | | Not found: -> CKSetup.Runner/6.0.1-C0008-local dependency.
   2018-05-30 15h44.18.0433244 i | | | | | | | | | < 
   2018-05-30 15h44.18.0433244 i | | | | | | | | < 
   2018-05-30 15h44.18.0433244   | | | | | | | | > Creating client remote store on 'file:///C:/Dev/LocalFeed/Release/CKSetupStore'.
   2018-05-30 15h44.18.0508124   | | | | | | | | | Opened store with 30 components.
   2018-05-30 15h44.18.0508124   | | | | | | | | | Local store opened on : 'C:\Dev\LocalFeed\Release\CKSetupStore'.
   2018-05-30 15h44.18.0508124   | | | | | | | | < 
   2018-05-30 15h44.18.0508124 i | | | | | | | | > Requesting Prototype store to complete the export.
   2018-05-30 15h44.18.0508124 i | | | | | | | | | > No remote store has been specified. Using prototype store only (file:///C:/Dev/LocalFeed/Release/CKSetupStore).
   2018-05-30 15h44.18.0508124   | | | | | | | | | | > Download from store: file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h44.18.0508124 i | | | | | | | | | | | > Finding locally available components.
   2018-05-30 15h44.18.0508124 i | | | | | | | | | | | | > Resolving dependencies for Net461.
   2018-05-30 15h44.18.0508124 W | | | | | | | | | | | | | Not found: -> CK.Setupable.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.18.0508124 W | | | | | | | | | | | | | Not found: -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.18.0508124 W | | | | | | | | | | | | | Not found: -> CK.StObj.Runtime/6.0.1-C0006-local dependency.
   2018-05-30 15h44.18.0508124 W | | | | | | | | | | | | | Not found: -> CKSetup.Runner/6.0.1-C0008-local dependency.
   2018-05-30 15h44.18.0508124 i | | | | | | | | | | | | < 
   2018-05-30 15h44.18.0508124 i | | | | | | | | | | | < 
   2018-05-30 15h44.18.0508124   | | | | | | | | | | | > Creating client remote store on 'https://cksetup.invenietis.net/'.
   2018-05-30 15h44.18.0508124   | | | | | | | | | | | < 
   2018-05-30 15h44.18.0508124 i | | | | | | | | | | | > Requesting Prototype store to complete the export.
   2018-05-30 15h44.18.0508124 i | | | | | | | | | | | | > No remote store has been specified. Using prototype store only (https://cksetup.invenietis.net/).
   2018-05-30 15h44.18.0508124   | | | | | | | | | | | | | > Download from store: https://cksetup.invenietis.net/.
   2018-05-30 15h44.18.1107849 i | | | | | | | | | | | | | | > Starting import from https://cksetup.invenietis.net/.
   2018-05-30 15h44.18.1107849 i | | | | | | | | | | | | | | | > Starting components import.
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838   | | | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | > Starting import from file:///C:/Dev/LocalFeed/Release/CKSetupStore.
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | | > Starting components import.
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838   | | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | > Starting import from file:///C:/Dev/LocalFeed/CI/CKSetupStore.
   2018-05-30 15h44.18.1112838 i | | | | | | | | | > Starting components import.
   2018-05-30 15h44.18.1112838 i | | | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | | | < 
   2018-05-30 15h44.18.1112838   | | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | | < 
   2018-05-30 15h44.18.1112838 i | | | | | < 
   2018-05-30 15h44.18.1112838 E | | | | | Missing required dependencies: -> CK.Setupable.Runtime/6.0.1-C0006-local, -> CK.SqlServer.Setup.Runtime/6.0.1-C0006-local, -> CK.StObj.Runtime/6.0.1-C0006-local, -> CKSetup.Runner/6.0.1-C0008-local.
   2018-05-30 15h44.18.1112838 i | | | | < 
   2018-05-30 15h44.18.1112838 i | | | < 
   2018-05-30 15h44.18.1112838 i | | | > Deleting temporary Working Directory.
   2018-05-30 15h44.18.1117827 i | | | < 
   2018-05-30 15h44.18.1117827 i | | <  | 1 conclusion:
                                 | |    | Failed
   2018-05-30 15h44.18.1117827 i | | > Closing Store.
   2018-05-30 15h44.18.1122821 i | | | > Closing Store.
   2018-05-30 15h44.18.1127819 i | | | < 
   2018-05-30 15h44.18.1127819 i | | < 
   2018-05-30 15h44.18.1127819 i | | > Closing Store.
   2018-05-30 15h44.18.1127819 i | | | > Closing Store.
   2018-05-30 15h44.18.1127819 i | | | < 
   2018-05-30 15h44.18.1127819 i | | < 
   2018-05-30 15h44.18.1127819 i | < 
   2018-05-30 15h44.18.1127819 i < 
